mqtt_hw:
  type: "cnr/control/MQTTRobotHW"
  appenders      : [file, screen]
  levels         : [trace, info]
  pattern_layout : "[%5p][%d{HH:mm:ss,SSS}][%50M:%04L][%24c] %m%n"
  file_name      : mqtt_hw
  sampling_period: 0.004
  diagnostic_period: 0.1
  maximum_missing_cycles: 100
  feedback_joint_state_timeout: 10

  joint_names:   
  - joint_0
  - joint_1
  - joint_2
  - joint_3
  - joint_4
  - joint_5
  - joint_6
  
  chain_ids: [ABB]
  base_links: [ fake_linear_axis]
  tool_links: [ link_6]
  
  base_link: "fake_linear_axis"
  tool_link: "link_6"
  robot_description_param: /robot_description
  robot_description_planning_param: /robot_description_planning
  kin_update_period: 0.004

  initial_position: [0.5, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0]
  
  use_delta_target_pos: false
  delta_pos_from_start: false
  
  use_real_robot: true
  
  #--- MQTT ---
  
  client_id: "MQTT_HW"
  host: 192.168.125.7    # drapebot
  #host: 172.31.1.11    # test with loris pc
  #host: localhost
  port: 1883
  
  feedback_mqtt_topic: "/robot_1/feedback"
  out_feedback_mqtt_topic: "/ITR_feedback"
  command_mqtt_topic:  "/robot_1/command"
  nominal_trajectory_topic: /joint_pos_target
  # --- end ---
  
  remap_source_args:
  - "/mqtt_hw/multichain_js_pub/joint_states"
  - "/mqtt_hw/js_pub/joint_states"
  remap_target_args:
  - "/joint_states"
  - "/joint_states"


  js_pub:
    type: cnr/control/JointStatePublisher
    controlled_joints: all
    kin_update_period : 0.004


  p_j:
    type: cnr/control/OpenLoopPositionController
    setpoint_topic_name: /joint_pos_target
    controlled_joints: all
    kin_update_period : 0.004
    
  multichain_js_pub:
    type: cnr/control/MultiChainStatePublisher
    controlled_joint: all
  
  
  
  
  
  
  
deformation_hw:
  type: cnr/control/TopicRobotHW
  appenders: [file, screen]
  levels: [trace, info]
  pattern_layout: "[%5p][%d{HH:mm:ss,SSS}][%M:%L][%c] %m%n"
  file_name: "deformation_hw"
  kin_update_period: 0.004
  sampling_period: 0.004
  diagnostic_period: 0.1
  feedback_joint_state_timeout: 20
  maximum_missing_cycles: 100
  
  joint_names:   
  - joint_0
  - joint_1
  - joint_2
  - joint_3
  - joint_4
  - joint_5
  - joint_6

  base_link: "fake_linear_axis"
  tool_link: "link_6"
  robot_description_param: /robot_description
  robot_description_planning_param: /robot_description_planning

  feedback_joint_state_topic: /joint_states
  command_joint_state_topic:  /joint_pos_target

  deformation_ctrl:
    type: "cnr/control/DeformationCtrl"
    controlled_joints: all
    kin_update_period: 0.004
    
    use_cartesian_reference: false                 # are you going to use a reference Pose or JointState?  default: false
    joint_target_topic:     "/interp_joint_pos_target"   # incoming joints setpoint topic 
    pose_target:            "/interp_target_cart_pose"   # incoming pose setpoint topic
    
    robot_base_frame  : fake_linear_axis
    robot_tip_frame   : link_6




plan_hw:
  type: cnr/control/TopicRobotHW
  appenders: [file, screen]
  levels: [trace, info]
  pattern_layout: "[%5p][%d{HH:mm:ss,SSS}][%M:%L][%c] %m%n"
  file_name: "plan_hw"
  
  joint_names:   
  - joint_0
  - joint_1
  - joint_2
  - joint_3
  - joint_4
  - joint_5
  - joint_6

  base_link: "fake_linear_axis"
  tool_link: "link_6"
  robot_description_param: /robot_description
  robot_description_planning_param: /robot_description_planning

  feedback_joint_state_topic: /joint_states
  command_joint_state_topic:  /interp_joint_pos_target
  sampling_period: 0.004
  diagnostic_period: 0.1
  feedback_joint_state_timeout: 20
  maximum_missing_cycles: 100

  remap_source_args:
  - "/plan_hw/microint/follow_joint_trajectory/cancel"
  - "/plan_hw/microint/follow_joint_trajectory/feedback"
  - "/plan_hw/microint/follow_joint_trajectory/goal"
  - "/plan_hw/microint/follow_joint_trajectory/result"
  - "/plan_hw/microint/follow_joint_trajectory/status"

  remap_target_args:
  - "abb_moveit_lab/follow_joint_trajectory/cancel"
  - "abb_moveit_lab/follow_joint_trajectory/feedback"
  - "abb_moveit_lab/follow_joint_trajectory/goal"
  - "abb_moveit_lab/follow_joint_trajectory/result"
  - "abb_moveit_lab/follow_joint_trajectory/status"
    
    
  microint:
    type: "cnr/control/ScaledFJTPosController"
    controlled_joints: all


  
  
  
  
  
